
abstract class FFAppConstants {
  static const List<String> region = [
    'Northeast',
    'Northwest',
    'Central',
    'Southeast',
    'Southwest'
  ];
  static const List<String> entity = [
    'Farmer',
    'Distributor',
    'Aggregator',
    'Food Hub',
    'Food Bank',
    'Hot / Cold Storage',
    'Final Recipient'
  ];
  static const List<String> counties = [
    'Adams',
    'Allen',
    'Bartholomew',
    'Benton',
    'Blackford',
    'Boone',
    'Brown',
    'Carroll',
    'Cass',
    'Clark',
    'Clay',
    'Clinton',
    'Crawford',
    'Daviess',
    'Dearborn',
    'Decatur',
    'DeKalb',
    'Delaware',
    'Dubois',
    'Elkhart',
    'Fayette',
    'Floyd',
    'Fountain',
    'Franklin',
    'Fulton',
    'Gibson',
    'Grant',
    'Greene',
    'Hamilton',
    'Hancock',
    'Harrison',
    'Hendricks',
    'Henry',
    'Howard',
    'Huntington',
    'Jackson',
    'Jasper',
    'Jay',
    'Jefferson',
    'Jennings',
    'Johnson',
    'Knox',
    'Kosciusko',
    'LaPorte',
    'Lagrange',
    'Lake',
    'Lawrence',
    'Madison',
    'Marion',
    'Marshall',
    'Martin',
    'Miami',
    'Monroe',
    'Montgomery',
    'Morgan',
    'Newton',
    'Noble',
    'Ohio',
    'Orange',
    'Owen',
    'Parke',
    'Perry',
    'Pike',
    'Porter',
    'Posey',
    'Pulaski',
    'Putnam',
    'Randolph',
    'Ripley',
    'Rush',
    'StJoseph',
    'Scott',
    'Shelby',
    'Spencer',
    'Starke',
    'Steuben',
    'Sullivan',
    'Switzerland',
    'Tippecanoe',
    'Tipton',
    'Union',
    'Vanderburgh',
    'Vermillion',
    'Vigo',
    'Wabash',
    'Warren',
    'Warrick',
    'Washington',
    'Wayne',
    'Wells',
    'White',
    'Whitley'
  ];
  static const List<String> cities = [
    'Alexandria',
    'Anderson',
    'Angola',
    'Attica',
    'Auburn',
    'Aurora',
    'Austin',
    'Batesville',
    'Bedford',
    'Beech Grove',
    'Berne',
    'Bicknell',
    'Bloomington',
    'Bluffton',
    'Boonville',
    'Brazil',
    'Butler',
    'Cannelton',
    'Carmel',
    'Charlestown',
    'Clinton',
    'Columbia City',
    'Columbus',
    'Connersville',
    'Covington',
    'Crawfordsville',
    'Crown Point',
    'Decatur',
    'Delphi',
    'Dunkirk',
    'East Chicago',
    'Elkhart',
    'Elwood',
    'Evansville',
    'Fishers',
    'Fort Wayne',
    'Frankfort',
    'Franklin',
    'Garrett',
    'Gary',
    'Gas City',
    'Goshen',
    'Greencastle',
    'Greendale',
    'Greenfield',
    'Greensburg',
    'Greenwood',
    'Hammond',
    'Hartford City',
    'Hobart',
    'Huntingburg',
    'Huntington',
    'Indianapolis',
    'Jasonville',
    'Jasper',
    'Jeffersonville',
    'Jonesboro',
    'Kendallville',
    'Knox',
    'Kokomo',
    'La Porte',
    'Lafayette',
    'Lake Station',
    'Lawrence',
    'Lawrenceburg',
    'Lebanon',
    'Ligonier',
    'Linton',
    'Logansport',
    'Loogootee',
    'Madison',
    'Marion',
    'Martinsville',
    'Michigan City',
    'Mishawaka',
    'Mitchell',
    'Monticello',
    'Montpelier',
    'Mount Vernon',
    'Muncie',
    'Nappanee',
    'New Albany',
    'New Castle',
    'New Haven',
    'Noblesville',
    'North Vernon',
    'Oakland City',
    'Peru',
    'Petersburg',
    'Plymouth',
    'Portage',
    'Portland',
    'Princeton',
    'Rensselaer',
    'Richmond',
    'Rising Sun',
    'Rochester',
    'Rockport',
    'Rushville',
    'Salem',
    'Scottsburg',
    'Seymour',
    'Shelbyville',
    'South Bend',
    'Southport',
    'Sullivan',
    'Tell City',
    'Terre Haute',
    'Tipton',
    'Union City',
    'Valparaiso',
    'Vincennes',
    'Wabash',
    'Warsaw',
    'Washington',
    'West Lafayette',
    'Westfield',
    'Whiting',
    'Winchester',
    'Woodburn'
  ];
  static const List<String> timeSlots = [
    '6:00 AM - 8:00 AM',
    '8:00 AM - 10:00 AM',
    '10:00 AM - 12:00 PM',
    '12:00 PM - 2:00 PM',
    '2:00 PM - 4:00 PM',
    '4:00 PM - 6:00 PM',
    '6:00 PM - 8:00 PM',
    '8:00 PM - 10:00 PM'
  ];
  static const String checkFarmer = 'Farmer';
  static const String checkOther = 'Other';
  static const String checkReceived = 'Received';
  static const String checkCompleted = 'Completed';
  static const String testEmail = 'greenjoshua@hotmail.com';
  static const String fromLFATeam = 'LFA Indiana <indiana@localfoodaccess.com>';
  static const String noDeliverySlots =
      'Recipient needs to select best delivery times first.';
}
